#!/usr/bin/env bash
set -euo pipefail

# Prepare an OSX-KVM checkout for macOS 15 (Sequoia) with
# SickCodes-style performance flags and explicit SMBIOS serial config.
#
# Usage:
#   scripts/prepare-osx-kvm-symphony.sh /path/to/OSX-KVM
#
# Optional env vars:
#   SYSTEM_SERIAL        e.g. C02XX00XXX00
#   MLB_SERIAL           e.g. C02700000QXJG36A8
#   SYSTEM_UUID          e.g. AAAAAAAA-BBBB-CCCC-DDDD-EEEEEEEEEEEE
#   ROM_HEX              e.g. 0016CB445566
#   SYMPHONY_SOURCE_DIR  absolute path of this repo for provisioning link/copy

REPO_DIR="${1:-}"
if [[ -z "$REPO_DIR" ]]; then
  echo "Usage: $0 /path/to/OSX-KVM" >&2
  exit 1
fi

if [[ ! -d "$REPO_DIR" ]]; then
  echo "OSX-KVM directory not found: $REPO_DIR" >&2
  exit 1
fi

if [[ ! -f "$REPO_DIR/OpenCore-Boot.sh" ]]; then
  echo "Expected OpenCore-Boot.sh not found in $REPO_DIR" >&2
  exit 1
fi

BOOT_SCRIPT="$REPO_DIR/OpenCore-Boot.sh"

if ! rg -q "vmware-cpuid-freq=on" "$BOOT_SCRIPT"; then
  perl -0pi -e 's/-cpu\s+Penryn,/-cpu Penryn,vmware-cpuid-freq=on,/g' "$BOOT_SCRIPT"
  echo "Added vmware-cpuid-freq=on CPU optimization."
fi

if ! rg -q "+avx2" "$BOOT_SCRIPT"; then
  perl -0pi -e 's/(\-cpu\s+[^\n]*?)\n/$1,+avx,+avx2,+bmi1,+bmi2,+fma,+xsave,+xsaveopt\n/g' "$BOOT_SCRIPT"
  echo "Added extended CPU feature flags."
fi

SYMPHONY_HOOK="$REPO_DIR/symphony-in-c-provision.sh"
cat > "$SYMPHONY_HOOK" <<'HOOK'
#!/usr/bin/env bash
set -euo pipefail

# Provision symphony-in-c inside guest after first boot.
# Run manually in guest shell or via your existing cloud-init/bootstrap method.

TARGET_DIR="${TARGET_DIR:-$HOME/symphony-in-c}"
if [[ -n "${SYMPHONY_SOURCE_DIR:-}" && -d "${SYMPHONY_SOURCE_DIR}" ]]; then
  rsync -a --delete "${SYMPHONY_SOURCE_DIR}/" "${TARGET_DIR}/"
else
  git clone https://github.com/ludoplex/symphony-in-c.git "${TARGET_DIR}"
fi

cd "${TARGET_DIR}/elixir"
mix local.hex --force
mix local.rebar --force
mix deps.get
mix compile
HOOK
chmod +x "$SYMPHONY_HOOK"

SERIALS_FILE="$REPO_DIR/.env.smbios"
cat > "$SERIALS_FILE" <<SERIALS
# Replace with values generated by macserial from OpenCorePkg/Utilities/macserial.
SYSTEM_SERIAL=${SYSTEM_SERIAL:-REPLACE_SYSTEM_SERIAL}
MLB_SERIAL=${MLB_SERIAL:-REPLACE_MLB_SERIAL}
SYSTEM_UUID=${SYSTEM_UUID:-REPLACE_SYSTEM_UUID}
ROM_HEX=${ROM_HEX:-REPLACE_ROM_HEX}
SERIALS

README_PATCH="$REPO_DIR/SYMPHONY_SETUP.md"
cat > "$README_PATCH" <<'DOC'
# Symphony-in-c on OSX-KVM (macOS 15 / Sequoia)

## Stability recommendation
- Yes: macOS 15 (Sequoia) is currently the latest mainstream stable macOS line.
- For best VM reliability, pin to the latest 15.x point release instead of moving to beta channels.

## Included customizations
1. `OpenCore-Boot.sh` gets extra SickCodes-style CPU optimizations.
2. `.env.smbios` stores SMBIOS serial placeholders.
3. `symphony-in-c-provision.sh` bootstraps the project and precompiles Elixir code.

## Generate serials
Use `macserial` and set matching values in `.env.smbios`:
- SystemSerialNumber
- MLB
- SystemUUID
- ROM

## Recommended launch workflow
1. Fetch a macOS 15 recovery image.
2. Boot installer and complete setup.
3. Inside the guest, run `./symphony-in-c-provision.sh` (or point `SYMPHONY_SOURCE_DIR` to a host mirror).
4. Snapshot the VM after first successful `mix compile`.
DOC

echo "Patched: $BOOT_SCRIPT"
echo "Created: $SYMPHONY_HOOK"
echo "Created: $SERIALS_FILE"
echo "Created: $README_PATCH"
